
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

DROP TABLE IF EXISTS public.bible_reading_items CASCADE;
DROP TABLE IF EXISTS public.conquistador_classes CASCADE;
DROP TABLE IF EXISTS public.specialties CASCADE;
DROP TABLE IF EXISTS public.specialty_areas CASCADE;
DROP TABLE IF EXISTS public.user_progress CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

DROP TABLE IF EXISTS public.user_challenges CASCADE;
DROP TABLE IF EXISTS public.user_board_progress CASCADE;
DROP TABLE IF EXISTS public.user_cards CASCADE;
DROP TABLE IF EXISTS public.board_cards CASCADE;
DROP TABLE IF EXISTS public.challenges CASCADE;
DROP TABLE IF EXISTS public.boards CASCADE;
DROP TABLE IF EXISTS public.cards CASCADE;
DROP TABLE IF EXISTS public.intercambios_internet CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;

-- Perfil
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name text,
  avatar_url text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Progreso (equivalente a localStorage en app/page.tsx)
-- unlocked_specialties: objeto { [specialtyId]: boolean } — pestaña Especialidades
-- class_requirements: objeto { [classId]: boolean[] } — requisitos por clase (orden = class-requirement-sections)
-- bible_reading_completed: objeto { [challengeId]: boolean } — ids como amigo-dia-1 (pestaña Biblia)
-- content_unlocks: desbloqueos futuros / actualizaciones (servidor o reglas)
CREATE TABLE public.user_progress (
  user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  unlocked_specialties jsonb NOT NULL DEFAULT '{}'::jsonb,
  class_requirements jsonb NOT NULL DEFAULT '{}'::jsonb,
  bible_reading_completed jsonb NOT NULL DEFAULT '{}'::jsonb,
  content_unlocks jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Catalogo de clases (CLASSES en conquistadores-data.ts)
CREATE TABLE public.conquistador_classes (
  id text PRIMARY KEY,
  name text NOT NULL,
  sort_order smallint NOT NULL
);

-- Catalogo de lectura biblica (BIBLE_CHALLENGES: id = classId + '-dia-' + dia)
CREATE TABLE public.bible_reading_items (
  id text PRIMARY KEY,
  class_id text NOT NULL REFERENCES public.conquistador_classes (id) ON DELETE CASCADE,
  day smallint NOT NULL,
  title text NOT NULL,
  UNIQUE (class_id, day)
);

-- Catalogo de especialidades (opcional: la app sigue usando TS como fuente; aqui para CMS / informes)
CREATE TABLE public.specialty_areas (
  id text PRIMARY KEY,
  name text NOT NULL,
  image text,
  border_class text,
  theme_color text,
  sort_order smallint NOT NULL DEFAULT 0
);

CREATE TABLE public.specialties (
  id text PRIMARY KEY,
  area_id text NOT NULL REFERENCES public.specialty_areas (id) ON DELETE CASCADE,
  name text NOT NULL,
  image text,
  sort_order smallint NOT NULL DEFAULT 0
);

CREATE INDEX bible_reading_items_class_idx ON public.bible_reading_items (class_id, day);
CREATE INDEX specialties_area_idx ON public.specialties (area_id);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conquistador_classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_reading_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.specialty_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.specialties ENABLE ROW LEVEL SECURITY;

CREATE POLICY profiles_select_own ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY profiles_insert_own ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY user_progress_select_own ON public.user_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY user_progress_insert_own ON public.user_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY user_progress_update_own ON public.user_progress FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY classes_read_all ON public.conquistador_classes FOR SELECT USING (true);
CREATE POLICY bible_read_all ON public.bible_reading_items FOR SELECT USING (true);
CREATE POLICY specialty_areas_read_all ON public.specialty_areas FOR SELECT USING (true);
CREATE POLICY specialties_read_all ON public.specialties FOR SELECT USING (true);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id) VALUES (NEW.id);
  INSERT INTO public.user_progress (user_id) VALUES (NEW.id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_new_user();

INSERT INTO public.conquistador_classes (id, name, sort_order) VALUES
  ('amigo', 'Amigo', 1),
  ('companero', 'Companero', 2),
  ('explorador', 'Explorador', 3),
  ('pionero', 'Pionero', 4),
  ('excursionista', 'Excursionista', 5),
  ('guia', 'Guia', 6);

INSERT INTO public.specialty_areas (id, name, image, border_class, theme_color, sort_order) VALUES
  ('actividades-misioneras', 'Actividades Misioneras', '/specialties/areas/misioneras.jpg', 'border-border', '#5b4bff', 1),
  ('naturaleza', 'Estudio de la Naturaleza', '/specialties/areas/naturaleza.jpg', 'border-border', '#ffffff', 2),
  ('arte-habilidades-manuales', 'Arte y Habilidades Manuales', '/specialties/areas/manuales.jpg', 'border-border', '#38bdf8', 3),
  ('recreacionales', 'Actividades Recreativas', '/specialties/areas/recreativas.jpg', 'border-border', '#22c55e', 4),
  ('salud-ciencia', 'Ciencia y Salud', '/specialties/areas/cienciaysalud.jpg', 'border-border', '#7c3aed', 5),
  ('agricolas', 'Actividades Agrícolas', '/specialties/areas/agricolas.jpg', 'border-border', '#8b5e34', 6),
  ('profesionales', 'Actividades Profesionales', '/specialties/areas/profesionales.jpg', 'border-border', '#ef4444', 7),
  ('domesticas', 'Actividades Domésticas', '/specialties/areas/domesticas.jpg', 'border-border', '#f97316', 8),
  ('adra', 'ADRA (Servicio y Acción Comunitaria)', '/specialties/areas/adra.jpg', 'border-border', '#a78bfa', 9);

INSERT INTO public.specialties (id, area_id, name, image, sort_order) VALUES
  ('adoracion-cristiana', 'actividades-misioneras', 'Adoración cristiana', '/specialties/items/adoracion-cristiana.png', 1),
  ('apocalipsis', 'actividades-misioneras', 'Apocalipsis', NULL, 2),
  ('arqueologia-biblica', 'actividades-misioneras', 'Arqueología bíblica', NULL, 3),
  ('arte-cristiano-de-predicar', 'actividades-misioneras', 'Arte cristiano de predicar', NULL, 4),
  ('arte-cristiano-de-predicar-avanzado', 'actividades-misioneras', 'Arte cristiano de predicar - Avanzado', NULL, 5),
  ('arte-de-narrar-historias-cristianas', 'actividades-misioneras', 'Arte de narrar historias cristianas', NULL, 6),
  ('arte-en-titeres', 'actividades-misioneras', 'Arte en títeres', NULL, 7),
  ('arte-en-titeres-avanzado', 'actividades-misioneras', 'Arte en títeres - Avanzado', NULL, 8),
  ('audio-y-sonido', 'actividades-misioneras', 'Audio y sonido', NULL, 9),
  ('audio-y-sonido-avanzado', 'actividades-misioneras', 'Audio y sonido - Avanzado', NULL, 10),
  ('aventurero-para-cristo', 'actividades-misioneras', 'Aventurero para Cristo', NULL, 11),
  ('braille', 'actividades-misioneras', 'Braille', NULL, 12),
  ('buena-conducta-escolar', 'actividades-misioneras', 'Buena conducta escolar', NULL, 13),
  ('ceremonias', 'actividades-misioneras', 'Ceremonias', NULL, 14),
  ('civismo-cristiano', 'actividades-misioneras', 'Civismo cristiano', NULL, 15),
  ('creacionismo', 'actividades-misioneras', 'Creacionismo', NULL, 16),
  ('creacionismo-avanzado', 'actividades-misioneras', 'Creacionismo - Avanzado', NULL, 17),
  ('critico-de-medios', 'actividades-misioneras', 'Crítico de medios', NULL, 18),
  ('cultura-sudamericana', 'actividades-misioneras', 'Cultura Sudamericana', NULL, 19),
  ('desfile-con-carros-alegoricos', 'actividades-misioneras', 'Desfile con carros alegóricos', NULL, 20),
  ('dramatizacion-cristiana', 'actividades-misioneras', 'Dramatización cristiana', NULL, 21),
  ('educacion-inclusiva', 'actividades-misioneras', 'Educación inclusiva', NULL, 22),
  ('escatologia', 'actividades-misioneras', 'Escatología', NULL, 23),
  ('espiritu-de-profecia', 'actividades-misioneras', 'Espíritu de Profecía', NULL, 24),
  ('estudio-de-lenguas', 'actividades-misioneras', 'Estudio de Lenguas', NULL, 25),
  ('estudio-de-lenguas-avanzado', 'actividades-misioneras', 'Estudio de Lenguas - Avanzado', NULL, 26),
  ('etnologia-cristiana', 'actividades-misioneras', 'Etnología cristiana', NULL, 27),
  ('evangelismo-personal', 'actividades-misioneras', 'Evangelismo personal', NULL, 28),
  ('evangelismo-web', 'actividades-misioneras', 'Evangelismo web', NULL, 29),
  ('evangelismo-web-avanzado', 'actividades-misioneras', 'Evangelismo web - Avanzado', NULL, 30),
  ('historiador-eclesiastico', 'actividades-misioneras', 'Historiador eclesiástico', NULL, 31),
  ('investigador-biblico', 'actividades-misioneras', 'Investigador bíblico', NULL, 32),
  ('interpretacion-biblica', 'actividades-misioneras', 'Interpretación bíblica', NULL, 33),
  ('inteligencia-emocional', 'actividades-misioneras', 'Inteligencia emocional', NULL, 34),
  ('lenguaje-de-senas', 'actividades-misioneras', 'Lenguaje de señas', NULL, 35),
  ('lenguaje-de-senas-avanzado', 'actividades-misioneras', 'Lenguaje de señas - Avanzado', NULL, 36),
  ('liderazgo-de-menores', 'actividades-misioneras', 'Liderazgo de menores', NULL, 37),
  ('libro-de-daniel', 'actividades-misioneras', 'Libro de Daniel', NULL, 38),
  ('marcado-de-biblia', 'actividades-misioneras', 'Marcado de Biblia', NULL, 39),
  ('marcado-de-biblia-avanzado', 'actividades-misioneras', 'Marcado de Biblia - Avanzado', NULL, 40),
  ('mayordomia', 'actividades-misioneras', 'Mayordomía', NULL, 41),
  ('mensajera-de-dios', 'actividades-misioneras', 'Mensajera de Dios', NULL, 42),
  ('pacificador-avanzado', 'actividades-misioneras', 'Pacificador - Avanzado', NULL, 43),
  ('parabolas-de-jesus', 'actividades-misioneras', 'Parábolas de Jesús', NULL, 44),
  ('patriotismo', 'actividades-misioneras', 'Patriotismo', NULL, 45),
  ('pioneros-adventistas', 'actividades-misioneras', 'Pioneros Adventistas', NULL, 46),
  ('predicador-evangelista', 'actividades-misioneras', 'Predicador evangelista', NULL, 47),
  ('predicador-evangelista-avanzado', 'actividades-misioneras', 'Predicador evangelista - Avanzado', NULL, 48),
  ('relaciones-saludables', 'actividades-misioneras', 'Relaciones saludables', NULL, 49),
  ('santuario', 'actividades-misioneras', 'Santuario', NULL, 50),
  ('temperancia', 'actividades-misioneras', 'Temperancia', NULL, 51),
  ('testificacion-de-menores', 'actividades-misioneras', 'Testificación de menores', NULL, 52),
  ('transmision-de-adoracion-online', 'actividades-misioneras', 'Transmisión de adoración online', NULL, 53),
  ('vida-familiar', 'actividades-misioneras', 'Vida familiar', NULL, 54),
  ('abejas-y-avispas', 'naturaleza', 'Abejas y avispas', NULL, 1),
  ('acuarios', 'naturaleza', 'Acuarios', NULL, 2),
  ('algas', 'naturaleza', 'Algas', NULL, 3),
  ('anfibios', 'naturaleza', 'Anfibios', NULL, 4),
  ('anfibios-avanzado', 'naturaleza', 'Anfibios - Avanzado', NULL, 5),
  ('animales-en-peligro-de-extincion', 'naturaleza', 'Animales en peligro de extinción', NULL, 6),
  ('animales-migratorios', 'naturaleza', 'Animales migratorios', NULL, 7),
  ('animales-nocivos', 'naturaleza', 'Animales nocivos', NULL, 8),
  ('animales-nocturnos', 'naturaleza', 'Animales nocturnos', NULL, 9),
  ('animales-venenosos', 'naturaleza', 'Animales venenosos', NULL, 10),
  ('aranas', 'naturaleza', 'Arañas', NULL, 11),
  ('arboles', 'naturaleza', 'Árboles', NULL, 12),
  ('arboles-avanzado', 'naturaleza', 'Árboles - Avanzado', NULL, 13),
  ('arbustos', 'naturaleza', 'Arbustos', NULL, 14),
  ('arbustos-avanzado', 'naturaleza', 'Arbustos - Avanzado', NULL, 15),
  ('arenas', 'naturaleza', 'Arenas', NULL, 16),
  ('astronomia', 'naturaleza', 'Astronomía', NULL, 17),
  ('astronomia-avanzado', 'naturaleza', 'Astronomía - Avanzado', NULL, 18),
  ('aves', 'naturaleza', 'Aves', NULL, 19),
  ('aves-avanzado', 'naturaleza', 'Aves - Avanzado', NULL, 20),
  ('aves-domesticas', 'naturaleza', 'Aves domésticas', NULL, 21),
  ('aves-mascotas', 'naturaleza', 'Aves mascotas', NULL, 22),
  ('aves-de-rapina', 'naturaleza', 'Aves de rapiña', NULL, 23),
  ('bacterias', 'naturaleza', 'Bacterias', NULL, 24),
  ('briofitas', 'naturaleza', 'Briófitas', NULL, 25),
  ('bromelias', 'naturaleza', 'Bromelias', NULL, 26),
  ('cactus', 'naturaleza', 'Cactus', NULL, 27),
  ('cactus-avanzado', 'naturaleza', 'Cactus - Avanzado', NULL, 28),
  ('camellos', 'naturaleza', 'Camellos', NULL, 29),
  ('cataratas', 'naturaleza', 'Cataratas', NULL, 30),
  ('cetaceos', 'naturaleza', 'Cetáceos', NULL, 31),
  ('ciencia-planetaria', 'naturaleza', 'Ciencia planetaria', NULL, 32),
  ('cigarras', 'naturaleza', 'Cigarras', NULL, 33),
  ('citologia', 'naturaleza', 'Citología', NULL, 34),
  ('climatologia', 'naturaleza', 'Climatología', NULL, 35),
  ('climatologia-avanzado', 'naturaleza', 'Climatología - Avanzado', NULL, 36),
  ('compostaje-casero', 'naturaleza', 'Compostaje casero', NULL, 37),
  ('conservacion-ambiental', 'naturaleza', 'Conservación ambiental', NULL, 38),
  ('crustaceos', 'naturaleza', 'Crustáceos', NULL, 39),
  ('dinosaurios', 'naturaleza', 'Dinosaurios', NULL, 40),
  ('ecologia', 'naturaleza', 'Ecología', NULL, 41),
  ('ecologia-avanzado', 'naturaleza', 'Ecología - Avanzado', NULL, 42),
  ('energia-renovable', 'naturaleza', 'Energía renovable', NULL, 43),
  ('equinodermos', 'naturaleza', 'Equinodermos', NULL, 44),
  ('estuarios', 'naturaleza', 'Estuarios', NULL, 45),
  ('eucaliptos', 'naturaleza', 'Eucaliptos', NULL, 46),
  ('fauna-marina', 'naturaleza', 'Fauna marina', NULL, 47),
  ('felinos', 'naturaleza', 'Felinos', NULL, 48),
  ('felinos-avanzado', 'naturaleza', 'Felinos - Avanzado', NULL, 49),
  ('fisiologia-vegetal', 'naturaleza', 'Fisiología vegetal', NULL, 50),
  ('flores', 'naturaleza', 'Flores', NULL, 51),
  ('flores-avanzado', 'naturaleza', 'Flores - Avanzado', NULL, 52),
  ('fosiles', 'naturaleza', 'Fósiles', NULL, 53),
  ('gramineas', 'naturaleza', 'Gramíneas', NULL, 54),
  ('gusanos', 'naturaleza', 'Gusanos', NULL, 55),
  ('gusanos-avanzado', 'naturaleza', 'Gusanos - Avanzado', NULL, 56),
  ('helechos', 'naturaleza', 'Helechos', NULL, 57),
  ('hierbas', 'naturaleza', 'Hierbas', NULL, 58),
  ('hongos', 'naturaleza', 'Hongos', NULL, 59),
  ('hormigas', 'naturaleza', 'Hormigas', NULL, 60),
  ('insectos', 'naturaleza', 'Insectos', NULL, 61),
  ('insectos-avanzado', 'naturaleza', 'Insectos - Avanzado', NULL, 62),
  ('liquenes', 'naturaleza', 'Líquenes', NULL, 63),
  ('mamiferos', 'naturaleza', 'Mamíferos', NULL, 64),
  ('mamiferos-avanzado', 'naturaleza', 'Mamíferos - Avanzado', NULL, 65),
  ('mamiferos-marinos', 'naturaleza', 'Mamíferos marinos', NULL, 66),
  ('mamiferos-pequenos-como-mascotas', 'naturaleza', 'Mamíferos pequeños como mascotas', NULL, 67),
  ('mariposas-y-polillas', 'naturaleza', 'Mariposas y polillas', NULL, 68),
  ('marsupiales', 'naturaleza', 'Marsupiales', NULL, 69),
  ('mimetismo-y-camuflaje', 'naturaleza', 'Mimetismo y camuflaje', NULL, 70),
  ('moluscos', 'naturaleza', 'Moluscos', NULL, 71),
  ('moluscos-avanzado', 'naturaleza', 'Moluscos - Avanzado', NULL, 72),
  ('murcielagos', 'naturaleza', 'Murciélagos', NULL, 73),
  ('murcielagos-avanzado', 'naturaleza', 'Murciélagos - Avanzado', NULL, 74),
  ('odonata', 'naturaleza', 'Odonata', NULL, 75),
  ('orquideas', 'naturaleza', 'Orquídeas', NULL, 76),
  ('orquideas-avanzado', 'naturaleza', 'Orquídeas - Avanzado', NULL, 77),
  ('palmeras', 'naturaleza', 'Palmeras', NULL, 78),
  ('papagayos-loros-y-periquitos', 'naturaleza', 'Papagayos, loros y periquitos', NULL, 79),
  ('peces', 'naturaleza', 'Peces', NULL, 80),
  ('peces-ornamentales', 'naturaleza', 'Peces ornamentales', NULL, 81),
  ('perros', 'naturaleza', 'Perros', NULL, 82),
  ('plantas-carnivoras', 'naturaleza', 'Plantas carnívoras', NULL, 83),
  ('plantas-caseras', 'naturaleza', 'Plantas caseras', NULL, 84),
  ('plantas-silvestres-comestibles', 'naturaleza', 'Plantas silvestres comestibles', NULL, 85),
  ('poriferos-y-cnidarios', 'naturaleza', 'Poríferos y cnidarios', NULL, 86),
  ('preservacion-de-recursos-hidricos', 'naturaleza', 'Preservación de recursos hídricos', NULL, 87),
  ('primates', 'naturaleza', 'Primates', NULL, 88),
  ('protozoarios', 'naturaleza', 'Protozoarios', NULL, 89),
  ('rastreo-de-animales', 'naturaleza', 'Rastreo de animales', NULL, 90),
  ('rastreo-de-animales-avanzado', 'naturaleza', 'Rastreo de animales - Avanzado', NULL, 91),
  ('rebanos-domesticos', 'naturaleza', 'Rebaños domésticos', NULL, 92),
  ('reciclaje', 'naturaleza', 'Reciclaje', NULL, 93),
  ('reciclaje-avanzado', 'naturaleza', 'Reciclaje - Avanzado', NULL, 94),
  ('reptiles', 'naturaleza', 'Reptiles', NULL, 95),
  ('reptiles-avanzado', 'naturaleza', 'Reptiles - Avanzado', NULL, 96),
  ('rocas-y-minerales', 'naturaleza', 'Rocas y minerales', NULL, 97),
  ('rocas-y-minerales-avanzado', 'naturaleza', 'Rocas y minerales - Avanzado', NULL, 98),
  ('semillas', 'naturaleza', 'Semillas', NULL, 99),
  ('semillas-avanzado', 'naturaleza', 'Semillas - Avanzado', NULL, 100),
  ('suelos', 'naturaleza', 'Suelos', NULL, 101),
  ('tiburones', 'naturaleza', 'Tiburones', NULL, 102),
  ('tortugas', 'naturaleza', 'Tortugas', NULL, 103),
  ('virus', 'naturaleza', 'Virus', NULL, 104),
  ('volcanes', 'naturaleza', 'Volcanes', NULL, 105),
  ('aeromodelismo', 'arte-habilidades-manuales', 'Aeromodelismo', NULL, 1),
  ('album-de-recortes', 'arte-habilidades-manuales', 'Álbum de recortes', NULL, 2),
  ('album-de-recortes-avanzado', 'arte-habilidades-manuales', 'Álbum de recortes - Avanzado', NULL, 3),
  ('alfareria', 'arte-habilidades-manuales', 'Alfarería', NULL, 4),
  ('amigurumi', 'arte-habilidades-manuales', 'Amigurumi', NULL, 5),
  ('arte-con-hilo', 'arte-habilidades-manuales', 'Arte con hilo', NULL, 6),
  ('arte-de-hacer-esteras', 'arte-habilidades-manuales', 'Arte de hacer esteras', NULL, 7),
  ('arte-de-trenzar', 'arte-habilidades-manuales', 'Arte de trenzar', NULL, 8),
  ('arte-de-trenzar-avanzado', 'arte-habilidades-manuales', 'Arte de trenzar - Avanzado', NULL, 9),
  ('arte-digital', 'arte-habilidades-manuales', 'Arte Digital', NULL, 10),
  ('arte-en-telar', 'arte-habilidades-manuales', 'Arte en telar', NULL, 11),
  ('automodelismo', 'arte-habilidades-manuales', 'Automodelismo', NULL, 12),
  ('batik', 'arte-habilidades-manuales', 'Batik', NULL, 13),
  ('biscuit', 'arte-habilidades-manuales', 'Biscuit', NULL, 14),
  ('bordado-en-punto-cruz', 'arte-habilidades-manuales', 'Bordado en punto cruz', NULL, 15),
  ('bordados', 'arte-habilidades-manuales', 'Bordados', NULL, 16),
  ('carrera-de-autitos-de-madera', 'arte-habilidades-manuales', 'Carrera de autitos de madera', NULL, 17),
  ('ceramica', 'arte-habilidades-manuales', 'Cerámica', NULL, 18),
  ('cesteria', 'arte-habilidades-manuales', 'Cestería', NULL, 19),
  ('construcciones-nativas', 'arte-habilidades-manuales', 'Construcciones nativas', NULL, 20),
  ('croche', 'arte-habilidades-manuales', 'Croché', NULL, 21),
  ('croche-avanzado', 'arte-habilidades-manuales', 'Croché - Avanzado', NULL, 22),
  ('cultura-nativa', 'arte-habilidades-manuales', 'Cultura nativa', NULL, 23),
  ('cultura-nativa-avanzado', 'arte-habilidades-manuales', 'Cultura nativa - Avanzado', NULL, 24),
  ('decoracion', 'arte-habilidades-manuales', 'Decoración', NULL, 25),
  ('decoracion-con-flores', 'arte-habilidades-manuales', 'Decoración con flores', NULL, 26),
  ('decoracion-de-tortas', 'arte-habilidades-manuales', 'Decoración de tortas', NULL, 27),
  ('decoupage', 'arte-habilidades-manuales', 'Decoupage', NULL, 28),
  ('dibujo-vectorial', 'arte-habilidades-manuales', 'Dibujo vectorial', NULL, 29),
  ('dibujo-y-pintura', 'arte-habilidades-manuales', 'Dibujo y pintura', NULL, 30),
  ('envoltorio', 'arte-habilidades-manuales', 'Envoltorio', NULL, 31),
  ('escultura', 'arte-habilidades-manuales', 'Escultura', NULL, 32),
  ('esmaltado-en-cobre', 'arte-habilidades-manuales', 'Esmaltado en cobre', NULL, 33),
  ('estampado-con-molde', 'arte-habilidades-manuales', 'Estampado con molde', NULL, 34),
  ('eva', 'arte-habilidades-manuales', 'EVA', NULL, 35),
  ('fabricacion-de-velas', 'arte-habilidades-manuales', 'Fabricación de velas', NULL, 36),
  ('faros', 'arte-habilidades-manuales', 'Faros', NULL, 37),
  ('filigrana', 'arte-habilidades-manuales', 'Filigrana', NULL, 38),
  ('filigrana-avanzado', 'arte-habilidades-manuales', 'Filigrana - Avanzado', NULL, 39),
  ('fotografia-digital', 'arte-habilidades-manuales', 'Fotografía digital', NULL, 40),
  ('fuxico', 'arte-habilidades-manuales', 'Fuxico', NULL, 41),
  ('genealogia', 'arte-habilidades-manuales', 'Genealogía', NULL, 42),
  ('globos-aeroestaticos', 'arte-habilidades-manuales', 'Globos aeroestáticos', NULL, 43),
  ('grabado-en-vidrio', 'arte-habilidades-manuales', 'Grabado en vidrio', NULL, 44),
  ('guitarra', 'arte-habilidades-manuales', 'Guitarra', NULL, 45),
  ('guitarra-avanzado', 'arte-habilidades-manuales', 'Guitarra - Avanzado', NULL, 46),
  ('herencia-cultural', 'arte-habilidades-manuales', 'Herencia cultural', NULL, 47),
  ('historietas-animadas', 'arte-habilidades-manuales', 'Historietas animadas', NULL, 48),
  ('letreros-y-carteles', 'arte-habilidades-manuales', 'Letreros y carteles', NULL, 49),
  ('lettering', 'arte-habilidades-manuales', 'Lettering', NULL, 50),
  ('macrame', 'arte-habilidades-manuales', 'Macramé', NULL, 51),
  ('modelaje-en-yeso', 'arte-habilidades-manuales', 'Modelaje en yeso', NULL, 52),
  ('modelaje-y-fabricacion-de-jabon', 'arte-habilidades-manuales', 'Modelaje y fabricación de jabón', NULL, 53),
  ('modelaje-y-fabricacion-de-jabon-avanzado', 'arte-habilidades-manuales', 'Modelaje y fabricación de jabón - Avanzado', NULL, 54),
  ('modelismo-espacial', 'arte-habilidades-manuales', 'Modelismo espacial', NULL, 55),
  ('modelismo-espacial-avanzado', 'arte-habilidades-manuales', 'Modelismo espacial - Avanzado', NULL, 56),
  ('modelismo-ferroviario', 'arte-habilidades-manuales', 'Modelismo ferroviario', NULL, 57),
  ('modelismo-naval', 'arte-habilidades-manuales', 'Modelismo naval', NULL, 58),
  ('musica-basico', 'arte-habilidades-manuales', 'Música - Básico', NULL, 59),
  ('musica-intermedio', 'arte-habilidades-manuales', 'Música - Intermedio', NULL, 60),
  ('musica-avanzado', 'arte-habilidades-manuales', 'Música - Avanzado', NULL, 61),
  ('origami', 'arte-habilidades-manuales', 'Origami', NULL, 62),
  ('origami-avanzado', 'arte-habilidades-manuales', 'Origami - Avanzado', NULL, 63),
  ('papel-mache', 'arte-habilidades-manuales', 'Papel maché', NULL, 64),
  ('papercraft', 'arte-habilidades-manuales', 'Papercraft', NULL, 65),
  ('patchwork', 'arte-habilidades-manuales', 'Patchwork', NULL, 66),
  ('pintura-en-tela', 'arte-habilidades-manuales', 'Pintura en tela', NULL, 67),
  ('pintura-en-vidrio', 'arte-habilidades-manuales', 'Pintura en vidrio', NULL, 68),
  ('pirograbado', 'arte-habilidades-manuales', 'Pirograbado', NULL, 69),
  ('plastico-canvas', 'arte-habilidades-manuales', 'Plástico canvas', NULL, 70),
  ('plastimodelismo', 'arte-habilidades-manuales', 'Plastimodelismo', NULL, 71),
  ('serigrafia', 'arte-habilidades-manuales', 'Serigrafía', NULL, 72),
  ('serigrafia-avanzado', 'arte-habilidades-manuales', 'Serigrafía - Avanzado', NULL, 73),
  ('silbatos', 'arte-habilidades-manuales', 'Silbatos', NULL, 74),
  ('tallado-en-madera', 'arte-habilidades-manuales', 'Tallado en madera', NULL, 75),
  ('tallado-en-piedra', 'arte-habilidades-manuales', 'Tallado en piedra', NULL, 76),
  ('tapiceria', 'arte-habilidades-manuales', 'Tapicería', NULL, 77),
  ('tejidos', 'arte-habilidades-manuales', 'Tejidos', NULL, 78),
  ('tejido', 'arte-habilidades-manuales', 'Tejido', NULL, 79),
  ('tejido-avanzado', 'arte-habilidades-manuales', 'Tejido - Avanzado', NULL, 80),
  ('trabajos-en-acrilico', 'arte-habilidades-manuales', 'Trabajos en acrílico', NULL, 81),
  ('trabajos-en-cuero', 'arte-habilidades-manuales', 'Trabajos en cuero', NULL, 82),
  ('trabajos-en-cuero-avanzado', 'arte-habilidades-manuales', 'Trabajos en cuero - Avanzado', NULL, 83),
  ('trabajos-en-madera', 'arte-habilidades-manuales', 'Trabajos en madera', NULL, 84),
  ('trabajos-en-metal', 'arte-habilidades-manuales', 'Trabajos en metal', NULL, 85),
  ('trabajos-en-pano-lenci', 'arte-habilidades-manuales', 'Trabajos en paño lenci', NULL, 86),
  ('trabajos-en-vidrio', 'arte-habilidades-manuales', 'Trabajos en vidrio', NULL, 87),
  ('acrobacia-y-equilibrio', 'recreacionales', 'Acrobacia y equilibrio', NULL, 1),
  ('arco-y-flecha', 'recreacionales', 'Arco y flecha', NULL, 2),
  ('arte-de-acampar', 'recreacionales', 'Arte de acampar', NULL, 3),
  ('atletismo', 'recreacionales', 'Atletismo', NULL, 4),
  ('basquetbol', 'recreacionales', 'Básquetbol', NULL, 5),
  ('bowling', 'recreacionales', 'Bowling', NULL, 6),
  ('buceo', 'recreacionales', 'Buceo', NULL, 7),
  ('canotaje', 'recreacionales', 'Canotaje', NULL, 8),
  ('caminata', 'recreacionales', 'Caminata', NULL, 9),
  ('caminata-avanzado', 'recreacionales', 'Caminata - Avanzado', NULL, 10),
  ('caminata-con-mochila', 'recreacionales', 'Caminata con mochila', NULL, 11),
  ('caminata-con-mochila-avanzado', 'recreacionales', 'Caminata con mochila - Avanzado', NULL, 12),
  ('campamento-i', 'recreacionales', 'Campamento I', NULL, 13),
  ('campamento-ii', 'recreacionales', 'Campamento II', NULL, 14),
  ('campamento-iii', 'recreacionales', 'Campamento III', NULL, 15),
  ('campamento-iv', 'recreacionales', 'Campamento IV', NULL, 16),
  ('campamento-en-bajas-temperaturas', 'recreacionales', 'Campamento en bajas temperaturas', NULL, 17),
  ('campamento-seguro', 'recreacionales', 'Campamento seguro', NULL, 18),
  ('campamento-seguro-avanzado', 'recreacionales', 'Campamento seguro - Avanzado', NULL, 19),
  ('campamento-consciente', 'recreacionales', 'Campamento consciente', NULL, 20),
  ('campori-seguro', 'recreacionales', 'Camporí seguro', NULL, 21),
  ('canicas', 'recreacionales', 'Canicas', NULL, 22),
  ('carritos-de-rueditas', 'recreacionales', 'Carritos de rueditas', NULL, 23),
  ('ciclismo', 'recreacionales', 'Ciclismo', NULL, 24),
  ('ciclismo-avanzado', 'recreacionales', 'Ciclismo - Avanzado', NULL, 25),
  ('cocina-en-horno-holandes', 'recreacionales', 'Cocina en horno holandés', NULL, 26),
  ('cocina-segura', 'recreacionales', 'Cocina segura', NULL, 27),
  ('coleccionista', 'recreacionales', 'Coleccionista', NULL, 28),
  ('cometas', 'recreacionales', 'Cometas', NULL, 29),
  ('comida-de-supervivencia', 'recreacionales', 'Comida de supervivencia', NULL, 30),
  ('construccion-de-canoas', 'recreacionales', 'Construcción de canoas', NULL, 31),
  ('construcciones-rusticas', 'recreacionales', 'Construcciones rústicas', NULL, 32),
  ('cubo-de-rubik', 'recreacionales', 'Cubo de Rubik', NULL, 33),
  ('tenis-de-mesa', 'recreacionales', 'Tenis de mesa', NULL, 34),
  ('deportes-paralimpicos', 'recreacionales', 'Deportes paralímpicos', NULL, 35),
  ('educacion-fisica', 'recreacionales', 'Educación física', NULL, 36),
  ('equitacion', 'recreacionales', 'Equitación', NULL, 37),
  ('escalada', 'recreacionales', 'Escalada', NULL, 38),
  ('escalada-avanzado', 'recreacionales', 'Escalada - Avanzado', NULL, 39),
  ('espeleologia', 'recreacionales', 'Espeleología', NULL, 40),
  ('espeleologia-avanzado', 'recreacionales', 'Espeleología - Avanzado', NULL, 41),
  ('esqui-acuatico', 'recreacionales', 'Esquí acuático', NULL, 42),
  ('esqui-alpino', 'recreacionales', 'Esquí alpino', NULL, 43),
  ('evolucion-en-orden-cerrado', 'recreacionales', 'Evolución en orden cerrado', NULL, 44),
  ('filatelia', 'recreacionales', 'Filatelia', NULL, 45),
  ('fogatas-y-cocina-al-aire-libre', 'recreacionales', 'Fogatas y cocina al aire libre', NULL, 46),
  ('futbol', 'recreacionales', 'Fútbol', NULL, 47),
  ('futbol-de-botones', 'recreacionales', 'Fútbol de botones', NULL, 48),
  ('futbol-sala', 'recreacionales', 'Fútbol sala', NULL, 49),
  ('geocaching', 'recreacionales', 'Geocaching', NULL, 50),
  ('geocaching-avanzado', 'recreacionales', 'Geocaching - Avanzado', NULL, 51),
  ('grandes-construcciones-rusticas', 'recreacionales', 'Grandes construcciones rústicas', NULL, 52),
  ('handbol', 'recreacionales', 'Hándbol', NULL, 53),
  ('intercambio-de-pines', 'recreacionales', 'Intercambio de pines', NULL, 54),
  ('kayak', 'recreacionales', 'Kayak', NULL, 55),
  ('letterboxing', 'recreacionales', 'Letterboxing', NULL, 56),
  ('liderazgo-al-aire-libre', 'recreacionales', 'Liderazgo al aire libre', NULL, 57),
  ('liderazgo-al-aire-libre-avanzado', 'recreacionales', 'Liderazgo al aire libre - Avanzado', NULL, 58),
  ('liderazgo-en-la-naturaleza', 'recreacionales', 'Liderazgo en la naturaleza', NULL, 59),
  ('liderazgo-en-la-naturaleza-avanzado', 'recreacionales', 'Liderazgo en la naturaleza - Avanzado', NULL, 60),
  ('monociclo', 'recreacionales', 'Monociclo', NULL, 61),
  ('mountain-bike', 'recreacionales', 'Mountain bike', NULL, 62),
  ('natacion-principiante-i', 'recreacionales', 'Natación - Principiante I', NULL, 63),
  ('natacion-principiante-ii', 'recreacionales', 'Natación - Principiante II', NULL, 64),
  ('natacion-intermedio-i', 'recreacionales', 'Natación - Intermedio I', NULL, 65),
  ('natacion-intermedio-ii', 'recreacionales', 'Natación - Intermedio II', NULL, 66),
  ('natacion-avanzado', 'recreacionales', 'Natación - Avanzado', NULL, 67),
  ('navegacion', 'recreacionales', 'Navegación', NULL, 68),
  ('navegacion-a-vela', 'recreacionales', 'Navegación a vela', NULL, 69),
  ('nudos-y-amarras', 'recreacionales', 'Nudos y amarras', NULL, 70),
  ('nudos-y-amarras-avanzado', 'recreacionales', 'Nudos y amarras - Avanzado', NULL, 71),
  ('numismatica', 'recreacionales', 'Numismática', NULL, 72),
  ('numismatica-avanzado', 'recreacionales', 'Numismática - Avanzado', NULL, 73),
  ('orden-cerrado', 'recreacionales', 'Orden cerrado', NULL, 74),
  ('orden-cerrado-avanzado', 'recreacionales', 'Orden cerrado - Avanzado', NULL, 75),
  ('orden-cerrado-instructor', 'recreacionales', 'Orden cerrado - Instructor', NULL, 76),
  ('orientacion', 'recreacionales', 'Orientación', NULL, 77),
  ('orientacion-con-gps', 'recreacionales', 'Orientación con GPS', NULL, 78),
  ('patines', 'recreacionales', 'Patines', NULL, 79),
  ('pionerismo', 'recreacionales', 'Pionerismo', NULL, 80),
  ('rafting', 'recreacionales', 'Rafting', NULL, 81),
  ('rapel', 'recreacionales', 'Rápel', NULL, 82),
  ('rapel-avanzado', 'recreacionales', 'Rápel - Avanzado', NULL, 83),
  ('rapel-instructor', 'recreacionales', 'Rápel - Instructor', NULL, 84),
  ('remo', 'recreacionales', 'Remo', NULL, 85),
  ('rescate-acuatico', 'recreacionales', 'Rescate acuático', NULL, 86),
  ('rescate-acuatico-avanzado', 'recreacionales', 'Rescate acuático - Avanzado', NULL, 87),
  ('saltos-ornamentales', 'recreacionales', 'Saltos ornamentales', NULL, 88),
  ('seguridad-basica-en-el-agua', 'recreacionales', 'Seguridad básica en el agua', NULL, 89),
  ('sendero-de-senales', 'recreacionales', 'Sendero de señales', NULL, 90),
  ('skate', 'recreacionales', 'Skate', NULL, 91),
  ('slackline', 'recreacionales', 'Slackline', NULL, 92),
  ('softbol', 'recreacionales', 'Sóftbol', NULL, 93),
  ('supervivencia-en-la-naturaleza', 'recreacionales', 'Supervivencia en la naturaleza', NULL, 94),
  ('tambores-y-percusion', 'recreacionales', 'Tambores y percusión', NULL, 95),
  ('telecartofilia', 'recreacionales', 'Telecartofilia', NULL, 96),
  ('trepar-arboles', 'recreacionales', 'Trepar árboles', NULL, 97),
  ('triatlon', 'recreacionales', 'Triatlón', NULL, 98),
  ('trompo', 'recreacionales', 'Trompo', NULL, 99),
  ('viajes-y-turismo', 'recreacionales', 'Viajes y turismo', NULL, 100),
  ('viajes-y-turismo-avanzado', 'recreacionales', 'Viajes y turismo - Avanzado', NULL, 101),
  ('vida-silvestre', 'recreacionales', 'Vida silvestre', NULL, 102),
  ('voleibol', 'recreacionales', 'Vóleibol', NULL, 103),
  ('wakeboard', 'recreacionales', 'Wakeboard', NULL, 104),
  ('waveboarding', 'recreacionales', 'Waveboarding', NULL, 105),
  ('windsurf', 'recreacionales', 'Windsurf', NULL, 106),
  ('alerta-roja', 'salud-ciencia', 'Alerta Roja', NULL, 1),
  ('anatomia-cristiana', 'salud-ciencia', 'Anatomía cristiana', NULL, 2),
  ('bioquimica', 'salud-ciencia', 'Bioquímica', NULL, 3),
  ('cientificos-cristianos', 'salud-ciencia', 'Científicos cristianos', NULL, 4),
  ('corazon-y-circulacion', 'salud-ciencia', 'Corazón y circulación', NULL, 5),
  ('digestion', 'salud-ciencia', 'Digestión', NULL, 6),
  ('enfermeria-basico', 'salud-ciencia', 'Enfermería básico', NULL, 7),
  ('experimentos-cientificos', 'salud-ciencia', 'Experimentos científicos', NULL, 8),
  ('fisica', 'salud-ciencia', 'Física', NULL, 9),
  ('habilidad-matematica-i', 'salud-ciencia', 'Habilidad matemática I', NULL, 10),
  ('habilidad-matematica-ii', 'salud-ciencia', 'Habilidad matemática II', NULL, 11),
  ('heredibilidad', 'salud-ciencia', 'Heredibilidad', NULL, 12),
  ('higiene-oral', 'salud-ciencia', 'Higiene oral', NULL, 13),
  ('higiene-oral-avanzado', 'salud-ciencia', 'Higiene oral - Avanzado', NULL, 14),
  ('huesos-musculos-y-articulaciones', 'salud-ciencia', 'Huesos, músculos y articulaciones', NULL, 15),
  ('metodologia-de-estudio', 'salud-ciencia', 'Metodología de estudio', NULL, 16),
  ('microscopia', 'salud-ciencia', 'Microscopía', NULL, 17),
  ('nutricion', 'salud-ciencia', 'Nutrición', NULL, 18),
  ('nutricion-avanzado', 'salud-ciencia', 'Nutrición - Avanzado', NULL, 19),
  ('optica', 'salud-ciencia', 'Óptica', NULL, 20),
  ('patrimonio-historico', 'salud-ciencia', 'Patrimonio histórico', NULL, 21),
  ('plantas-medicinales', 'salud-ciencia', 'Plantas medicinales', NULL, 22),
  ('prevencion-de-enfermedades-tropicales', 'salud-ciencia', 'Prevención de enfermedades tropicales', NULL, 23),
  ('primeros-auxilios-basico', 'salud-ciencia', 'Primeros auxilios - Básico', NULL, 24),
  ('primeros-auxilios-intermedio', 'salud-ciencia', 'Primeros auxilios - Intermedio', NULL, 25),
  ('primeros-auxilios-avanzado', 'salud-ciencia', 'Primeros auxilios - Avanzado', NULL, 26),
  ('quimica', 'salud-ciencia', 'Química', NULL, 27),
  ('reanimacion-cardiopulmonar', 'salud-ciencia', 'Reanimación cardiopulmonar', NULL, 28),
  ('remedios-naturales', 'salud-ciencia', 'Remedios naturales', NULL, 29),
  ('rescate-basico', 'salud-ciencia', 'Rescate básico', NULL, 30),
  ('salud-mental', 'salud-ciencia', 'Salud mental', NULL, 31),
  ('salud-y-cura', 'salud-ciencia', 'Salud y cura', NULL, 32),
  ('sangre-y-defensa-del-cuerpo', 'salud-ciencia', 'Sangre y defensa del cuerpo', NULL, 33),
  ('sexualidad-humana', 'salud-ciencia', 'Sexualidad humana', NULL, 34),
  ('sistema-nervioso', 'salud-ciencia', 'Sistema nervioso', NULL, 35),
  ('sistema-respiratorio', 'salud-ciencia', 'Sistema respiratorio', NULL, 36),
  ('transito-seguro', 'salud-ciencia', 'Tránsito seguro', NULL, 37),
  ('vacunas', 'salud-ciencia', 'Vacunas', NULL, 38),
  ('zoonosis', 'salud-ciencia', 'Zoonosis', NULL, 39),
  ('agricultura', 'agricolas', 'Agricultura', NULL, 1),
  ('agricultura-familiar-de-subsistencia', 'agricolas', 'Agricultura familiar de subsistencia', NULL, 2),
  ('apicultura', 'agricolas', 'Apicultura', NULL, 3),
  ('avicultura', 'agricolas', 'Avicultura', NULL, 4),
  ('cria-de-caballos', 'agricolas', 'Cría de caballos', NULL, 5),
  ('cria-de-cabras', 'agricolas', 'Cría de cabras', NULL, 6),
  ('cria-de-ovejas', 'agricolas', 'Cría de ovejas', NULL, 7),
  ('cria-de-palomas', 'agricolas', 'Cría de palomas', NULL, 8),
  ('fruticultura-i', 'agricolas', 'Fruticultura I', NULL, 9),
  ('fruticultura-ii', 'agricolas', 'Fruticultura II', NULL, 10),
  ('floricultura', 'agricolas', 'Floricultura', NULL, 11),
  ('ganaderia', 'agricolas', 'Ganadería', NULL, 12),
  ('ganaderia-lechera', 'agricolas', 'Ganadería lechera', NULL, 13),
  ('jardineria-y-horticultura', 'agricolas', 'Jardinería y horticultura', NULL, 14),
  ('pesca', 'agricolas', 'Pesca', NULL, 15),
  ('paisajismo', 'agricolas', 'Paisajismo', NULL, 16),
  ('administracion', 'profesionales', 'Administración', NULL, 1),
  ('albanileria', 'profesionales', 'Albañilería', NULL, 2),
  ('bibliotecologia', 'profesionales', 'Bibliotecología', NULL, 3),
  ('blogs', 'profesionales', 'Blogs', NULL, 4),
  ('carpinteria', 'profesionales', 'Carpintería', NULL, 5),
  ('codigo-de-semaforo', 'profesionales', 'Código de semáforo', NULL, 6),
  ('codigo-morse', 'profesionales', 'Código morse', NULL, 7),
  ('computacion-i-basico', 'profesionales', 'Computación I - Básico', NULL, 8),
  ('computacion-ii-intermedio', 'profesionales', 'Computación II - Intermedio', NULL, 9),
  ('computacion-iii-regular', 'profesionales', 'Computación III - Regular', NULL, 10),
  ('computacion-iv-avanzado', 'profesionales', 'Computación IV - Avanzado', NULL, 11),
  ('computacion-v-especializado', 'profesionales', 'Computación V - Especializado', NULL, 12),
  ('contabilidad', 'profesionales', 'Contabilidad', NULL, 13),
  ('corte-y-confeccion', 'profesionales', 'Corte y confección', NULL, 14),
  ('corte-y-confeccion-avanzado', 'profesionales', 'Corte y confección - Avanzado', NULL, 15),
  ('cuidado-y-adiestramiento-de-perros', 'profesionales', 'Cuidado y adiestramiento de perros', NULL, 16),
  ('cuidado-y-mantenimiento-de-guitarras', 'profesionales', 'Cuidado y mantenimiento de guitarras', NULL, 17),
  ('desarrollo-de-software', 'profesionales', 'Desarrollo de software', NULL, 18),
  ('disenador-web-basico', 'profesionales', 'Diseñador web - Básico', NULL, 19),
  ('disenador-web-avanzado', 'profesionales', 'Diseñador web - Avanzado', NULL, 20),
  ('ebanisteria', 'profesionales', 'Ebanistería', NULL, 21),
  ('electricidad', 'profesionales', 'Electricidad', NULL, 22),
  ('electronica', 'profesionales', 'Electrónica', NULL, 23),
  ('empapelado-de-pared', 'profesionales', 'Empapelado de pared', NULL, 24),
  ('encuadernacion', 'profesionales', 'Encuadernación', NULL, 25),
  ('ensamblaje-y-mantenimiento-de-computadoras', 'profesionales', 'Ensamblaje y mantenimiento de computadoras', NULL, 26),
  ('ensenanza', 'profesionales', 'Enseñanza', NULL, 27),
  ('evangelismo', 'profesionales', 'Evangelismo', NULL, 28),
  ('fotografia', 'profesionales', 'Fotografía', NULL, 29),
  ('gasfiteria', 'profesionales', 'Gasfitería', NULL, 30),
  ('imprenta', 'profesionales', 'Imprenta', NULL, 31),
  ('informatica-programable', 'profesionales', 'Informática programable', NULL, 32),
  ('internet', 'profesionales', 'Internet', NULL, 33),
  ('internet-avanzado', 'profesionales', 'Internet - Avanzado', NULL, 34),
  ('interprete-de-lenguaje-de-senas', 'profesionales', 'Intérprete de lenguaje de señas', NULL, 35),
  ('logistica', 'profesionales', 'Logística', NULL, 36),
  ('manejo-y-mantenimiento-de-impresoras', 'profesionales', 'Manejo y mantenimiento de impresoras', NULL, 37),
  ('mantenimiento-de-bicicletas', 'profesionales', 'Mantenimiento de bicicletas', NULL, 38),
  ('marketing', 'profesionales', 'Marketing', NULL, 39),
  ('marketing-avanzado', 'profesionales', 'Marketing - Avanzado', NULL, 40),
  ('mecanica-automotriz', 'profesionales', 'Mecánica automotriz', NULL, 41),
  ('mecanica-de-motores-pequenos', 'profesionales', 'Mecánica de motores pequeños', NULL, 42),
  ('modelado-textil', 'profesionales', 'Modelado textil', NULL, 43),
  ('nociones-de-economia', 'profesionales', 'Nociones de economía', NULL, 44),
  ('nociones-de-derecho', 'profesionales', 'Nociones de derecho', NULL, 45),
  ('peluqueria', 'profesionales', 'Peluquería', NULL, 46),
  ('periodismo', 'profesionales', 'Periodismo', NULL, 47),
  ('pintura-de-paredes-exteriores', 'profesionales', 'Pintura de paredes exteriores', NULL, 48),
  ('pintura-de-paredes-interiores', 'profesionales', 'Pintura de paredes interiores', NULL, 49),
  ('produccion-de-video', 'profesionales', 'Producción de video', NULL, 50),
  ('radioaficionado', 'profesionales', 'Radioaficionado', NULL, 51),
  ('reparacion-de-zapatos', 'profesionales', 'Reparación de zapatos', NULL, 52),
  ('restauracion-y-conservacion-de-documentos', 'profesionales', 'Restauración y conservación de documentos', NULL, 53),
  ('sastreria', 'profesionales', 'Sastrería', NULL, 54),
  ('secretariado', 'profesionales', 'Secretariado', NULL, 55),
  ('seguridad-contra-incendios', 'profesionales', 'Seguridad contra incendios', NULL, 56),
  ('seguridad-en-redes-sociales', 'profesionales', 'Seguridad en redes sociales', NULL, 57),
  ('silvicultura', 'profesionales', 'Silvicultura', NULL, 58),
  ('soldadura', 'profesionales', 'Soldadura', NULL, 59),
  ('taquigrafia', 'profesionales', 'Taquigrafía', NULL, 60),
  ('ventas', 'profesionales', 'Ventas', NULL, 61),
  ('produccion-de-pizzas', 'domesticas', 'Producción de pizzas', NULL, 1),
  ('arte-culinario', 'domesticas', 'Arte culinario', NULL, 2),
  ('tecnicas-de-lavanderia', 'domesticas', 'Técnicas de Lavandería', NULL, 3),
  ('cuidado-del-bebe', 'domesticas', 'Cuidado del bebé', NULL, 4),
  ('atencion-y-aseo-del-hogar', 'domesticas', 'Atención y aseo del hogar', NULL, 5),
  ('tecnicas-de-conservacion', 'domesticas', 'Técnicas de conservación', NULL, 6),
  ('presupuesto-familiar', 'domesticas', 'Presupuesto familiar', NULL, 7),
  ('panificacion', 'domesticas', 'Panificación', NULL, 8),
  ('arte-culinario-avanzado', 'domesticas', 'Arte culinario Avanzado', NULL, 9),
  ('costura-basica', 'domesticas', 'Costura básica', NULL, 10),
  ('comidas-tipicas', 'domesticas', 'Comidas típicas', NULL, 11),
  ('alimentos-congelados', 'domesticas', 'Alimentos congelados', NULL, 12),
  ('deshidratacion-de-alimentos', 'domesticas', 'Deshidratación de alimentos', NULL, 13),
  ('alfabetizacion', 'adra', 'Alfabetización', NULL, 1),
  ('alivio-del-hambre', 'adra', 'Alivio del hambre', NULL, 2),
  ('desarrollo-comunitario', 'adra', 'Desarrollo comunitario', NULL, 3),
  ('evaluacion-de-la-comunidad', 'adra', 'Evaluación de la comunidad', NULL, 4),
  ('reasentamiento-de-refugiados', 'adra', 'Reasentamiento de refugiados', NULL, 5),
  ('resolucion-de-conflictos', 'adra', 'Resolución de conflictos', NULL, 6),
  ('respuesta-a-emergencias-y-desastres', 'adra', 'Respuesta a emergencias y desastres', NULL, 7),
  ('respuesta-a-emergencias-y-desastres-avanzado', 'adra', 'Respuesta a emergencias y desastres - Avanzado', NULL, 8),
  ('servicio-comunitario', 'adra', 'Servicio comunitario', NULL, 9);

INSERT INTO public.bible_reading_items (id, class_id, day, title) VALUES
  ('amigo-dia-1', 'amigo', 1, 'Gn 1'),
  ('amigo-dia-2', 'amigo', 2, 'Gn 2'),
  ('amigo-dia-3', 'amigo', 3, 'Gn 3'),
  ('amigo-dia-4', 'amigo', 4, 'Gn 4:1-16'),
  ('amigo-dia-5', 'amigo', 5, 'Gn 6:11-22'),
  ('amigo-dia-6', 'amigo', 6, 'Gn 7'),
  ('amigo-dia-7', 'amigo', 7, 'Gn 8'),
  ('amigo-dia-8', 'amigo', 8, 'Gn 9:1-19'),
  ('amigo-dia-9', 'amigo', 9, 'Gn 11:1-9'),
  ('amigo-dia-10', 'amigo', 10, 'Gn 12:1-10'),
  ('amigo-dia-11', 'amigo', 11, 'Gn 13'),
  ('amigo-dia-12', 'amigo', 12, 'Gn 14:18-24'),
  ('amigo-dia-13', 'amigo', 13, 'Gn 15'),
  ('amigo-dia-14', 'amigo', 14, 'Gn 17:1-8; 15-22'),
  ('amigo-dia-15', 'amigo', 15, 'Gn 18:1-15'),
  ('amigo-dia-16', 'amigo', 16, 'Gn 18:16-33'),
  ('amigo-dia-17', 'amigo', 17, 'Gn 19:1-29'),
  ('amigo-dia-18', 'amigo', 18, 'Gn 21:1-21'),
  ('amigo-dia-19', 'amigo', 19, 'Gn 22:1-19'),
  ('amigo-dia-20', 'amigo', 20, 'Gn 23'),
  ('amigo-dia-21', 'amigo', 21, 'Gn 24:1-46,48'),
  ('amigo-dia-22', 'amigo', 22, 'Gn 24:52-67'),
  ('amigo-dia-23', 'amigo', 23, 'Gn 27'),
  ('amigo-dia-24', 'amigo', 24, 'Gn 28'),
  ('amigo-dia-25', 'amigo', 25, 'Gn 29'),
  ('amigo-dia-26', 'amigo', 26, 'Gn 30:25-31; 31:2-3,17-18'),
  ('amigo-dia-27', 'amigo', 27, 'Gn 32'),
  ('amigo-dia-28', 'amigo', 28, 'Gn 33'),
  ('amigo-dia-29', 'amigo', 29, 'Gn 37'),
  ('amigo-dia-30', 'amigo', 30, 'Gn 39'),
  ('amigo-dia-31', 'amigo', 31, 'Gn 40'),
  ('amigo-dia-32', 'amigo', 32, 'Gn 41'),
  ('amigo-dia-33', 'amigo', 33, 'Gn 42'),
  ('amigo-dia-34', 'amigo', 34, 'Gn 43'),
  ('amigo-dia-35', 'amigo', 35, 'Gn 44'),
  ('amigo-dia-36', 'amigo', 36, 'Gn 45'),
  ('amigo-dia-37', 'amigo', 37, 'Gn 47'),
  ('amigo-dia-38', 'amigo', 38, 'Gn 50'),
  ('amigo-dia-39', 'amigo', 39, 'Éx 1'),
  ('amigo-dia-40', 'amigo', 40, 'Éx 2'),
  ('amigo-dia-41', 'amigo', 41, 'Éx 3'),
  ('amigo-dia-42', 'amigo', 42, 'Éx 4:1-17; 27-31'),
  ('amigo-dia-43', 'amigo', 43, 'Éx 5'),
  ('amigo-dia-44', 'amigo', 44, 'Éx 7'),
  ('amigo-dia-45', 'amigo', 45, 'Éx 8'),
  ('amigo-dia-46', 'amigo', 46, 'Éx 9'),
  ('amigo-dia-47', 'amigo', 47, 'Éx 10, 11'),
  ('amigo-dia-48', 'amigo', 48, 'Éx 12'),
  ('amigo-dia-49', 'amigo', 49, 'Éx 13:17-22; 14'),
  ('amigo-dia-50', 'amigo', 50, 'Éx 15:22-27; 16'),
  ('amigo-dia-51', 'amigo', 51, 'Éx 17'),
  ('amigo-dia-52', 'amigo', 52, 'Éx 18'),
  ('amigo-dia-53', 'amigo', 53, 'Éx 19'),
  ('amigo-dia-54', 'amigo', 54, 'Éx 20'),
  ('amigo-dia-55', 'amigo', 55, 'Éx 24'),
  ('amigo-dia-56', 'amigo', 56, 'Éx 32'),
  ('amigo-dia-57', 'amigo', 57, 'Éx 33'),
  ('amigo-dia-58', 'amigo', 58, 'Éx 34:1-14,29-35'),
  ('amigo-dia-59', 'amigo', 59, 'Éx 35:4-29; 40'),
  ('companero-dia-1', 'companero', 1, 'Lv 11'),
  ('companero-dia-2', 'companero', 2, 'Nm 9:15-23'),
  ('companero-dia-3', 'companero', 3, 'Nm 11'),
  ('companero-dia-4', 'companero', 4, 'Nm 12'),
  ('companero-dia-5', 'companero', 5, 'Nm 13'),
  ('companero-dia-6', 'companero', 6, 'Nm 14:1-38'),
  ('companero-dia-7', 'companero', 7, 'Nm 16'),
  ('companero-dia-8', 'companero', 8, 'Nm 17'),
  ('companero-dia-9', 'companero', 9, 'Nm 20:1-13; 22-29'),
  ('companero-dia-10', 'companero', 10, 'Nm 21:4-9'),
  ('companero-dia-11', 'companero', 11, 'Nm 22'),
  ('companero-dia-12', 'companero', 12, 'Nm 23; 24:1-10'),
  ('companero-dia-13', 'companero', 13, 'Dt 1:1-17, 4:1-8'),
  ('companero-dia-14', 'companero', 14, 'Dt 32:1-43'),
  ('companero-dia-15', 'companero', 15, 'Dt 33'),
  ('companero-dia-16', 'companero', 16, 'Dt 34'),
  ('companero-dia-17', 'companero', 17, 'Js 1'),
  ('companero-dia-18', 'companero', 18, 'Js 2'),
  ('companero-dia-19', 'companero', 19, 'Js 3'),
  ('companero-dia-20', 'companero', 20, 'Js 4'),
  ('companero-dia-21', 'companero', 21, 'Js 5:10; 6'),
  ('companero-dia-22', 'companero', 22, 'Js 7'),
  ('companero-dia-23', 'companero', 23, 'Js 9'),
  ('companero-dia-24', 'companero', 24, 'Js 24:1-15; 29'),
  ('companero-dia-25', 'companero', 25, 'Jz 6'),
  ('companero-dia-26', 'companero', 26, 'Jz 7'),
  ('companero-dia-27', 'companero', 27, 'Jz 13:1-18; 14'),
  ('companero-dia-28', 'companero', 28, 'Jz 15'),
  ('companero-dia-29', 'companero', 29, 'Jz 16'),
  ('companero-dia-30', 'companero', 30, 'Rt 1'),
  ('companero-dia-31', 'companero', 31, 'Rt 2,3'),
  ('companero-dia-32', 'companero', 32, 'Rt 4'),
  ('companero-dia-33', 'companero', 33, '1 Sm 1'),
  ('companero-dia-34', 'companero', 34, '1 Sm 2'),
  ('companero-dia-35', 'companero', 35, '1 Sm 3'),
  ('companero-dia-36', 'companero', 36, '1 Sm 4'),
  ('companero-dia-37', 'companero', 37, '1 Sm 5'),
  ('companero-dia-38', 'companero', 38, '1 Sm 6'),
  ('companero-dia-39', 'companero', 39, '1 Sm 8'),
  ('companero-dia-40', 'companero', 40, '1 Sm 9'),
  ('companero-dia-41', 'companero', 41, '1 Sm 10;11:12-15'),
  ('companero-dia-42', 'companero', 42, '1 Sm 12'),
  ('companero-dia-43', 'companero', 43, '1 Sm 13'),
  ('companero-dia-44', 'companero', 44, '1 Sm 15'),
  ('companero-dia-45', 'companero', 45, '1 Sm 16'),
  ('companero-dia-46', 'companero', 46, '1 Sm 17'),
  ('companero-dia-47', 'companero', 47, '1 Sm 18:1-19'),
  ('companero-dia-48', 'companero', 48, '1 Sm 20'),
  ('companero-dia-49', 'companero', 49, '1 Sm 21:1-7; 22'),
  ('companero-dia-50', 'companero', 50, '1 Sm 24'),
  ('companero-dia-51', 'companero', 51, '1 Sm 25'),
  ('companero-dia-52', 'companero', 52, '1 Sm 26'),
  ('companero-dia-53', 'companero', 53, '1 Sm 31'),
  ('companero-dia-54', 'companero', 54, '2 Sm 1'),
  ('companero-dia-55', 'companero', 55, '2 Sm 5'),
  ('companero-dia-56', 'companero', 56, '2 Sm 6'),
  ('companero-dia-57', 'companero', 57, '2 Sm 7'),
  ('companero-dia-58', 'companero', 58, '2 Sm 9'),
  ('companero-dia-59', 'companero', 59, '2 Sm 11; 12:1-25'),
  ('companero-dia-60', 'companero', 60, '2 Sm 15'),
  ('companero-dia-61', 'companero', 61, '2 Sm 18'),
  ('explorador-dia-1', 'explorador', 1, 'Primer Libro de los Reyes 1:28-53'),
  ('explorador-dia-2', 'explorador', 2, 'Primer Libro de los Reyes 3'),
  ('explorador-dia-3', 'explorador', 3, 'Primer Libro de los Reyes 4:20-34'),
  ('explorador-dia-4', 'explorador', 4, 'Primer Libro de los Reyes 5-6'),
  ('explorador-dia-5', 'explorador', 5, 'Primer Libro de los Reyes 8:12-60'),
  ('explorador-dia-6', 'explorador', 6, 'Primer Libro de los Reyes 10'),
  ('explorador-dia-7', 'explorador', 7, 'Primer Libro de los Reyes 11:6-43'),
  ('explorador-dia-8', 'explorador', 8, 'Primer Libro de los Reyes 12'),
  ('explorador-dia-9', 'explorador', 9, 'Primer Libro de los Reyes 16:29-33; 17:1-7'),
  ('explorador-dia-10', 'explorador', 10, 'Primer Libro de los Reyes 17:8-24'),
  ('explorador-dia-11', 'explorador', 11, 'Primer Libro de los Reyes 18'),
  ('explorador-dia-12', 'explorador', 12, 'Primer Libro de los Reyes 19'),
  ('explorador-dia-13', 'explorador', 13, 'Primer Libro de los Reyes 21'),
  ('explorador-dia-14', 'explorador', 14, 'Segundo Libro de los Reyes 2'),
  ('explorador-dia-15', 'explorador', 15, 'Segundo Libro de los Reyes 4:1-7'),
  ('explorador-dia-16', 'explorador', 16, 'Segundo Libro de los Reyes 4:8-41'),
  ('explorador-dia-17', 'explorador', 17, 'Segundo Libro de los Reyes 5'),
  ('explorador-dia-18', 'explorador', 18, 'Segundo Libro de los Reyes 6:1-23'),
  ('explorador-dia-19', 'explorador', 19, 'Segundo Libro de los Reyes 6:24-33; 7'),
  ('explorador-dia-20', 'explorador', 20, 'Segundo Libro de los Reyes 20'),
  ('explorador-dia-21', 'explorador', 21, 'Segundo Libro de los Reyes 22'),
  ('explorador-dia-22', 'explorador', 22, 'Segundo Libro de los Reyes 23:36-37; 24; 25:1-7'),
  ('explorador-dia-23', 'explorador', 23, 'Segundo Libro de Crónicas 24:1-14'),
  ('explorador-dia-24', 'explorador', 24, 'Segundo Libro de Crónicas 36'),
  ('explorador-dia-25', 'explorador', 25, 'Libro de Esdras 1'),
  ('explorador-dia-26', 'explorador', 26, 'Libro de Esdras 3; 6:14-15'),
  ('explorador-dia-27', 'explorador', 27, 'Libro de Nehemías 1'),
  ('explorador-dia-28', 'explorador', 28, 'Libro de Nehemías 2'),
  ('explorador-dia-29', 'explorador', 29, 'Libro de Nehemías 4'),
  ('explorador-dia-30', 'explorador', 30, 'Libro de Nehemías 8'),
  ('explorador-dia-31', 'explorador', 31, 'Libro de Ester 1'),
  ('explorador-dia-32', 'explorador', 32, 'Libro de Ester 2'),
  ('explorador-dia-33', 'explorador', 33, 'Libro de Ester 3'),
  ('explorador-dia-34', 'explorador', 34, 'Libro de Ester 4'),
  ('explorador-dia-35', 'explorador', 35, 'Libro de Ester 5'),
  ('explorador-dia-36', 'explorador', 36, 'Libro de Ester 6'),
  ('explorador-dia-37', 'explorador', 37, 'Libro de Ester 7-8'),
  ('explorador-dia-38', 'explorador', 38, 'Libro de Job 1'),
  ('explorador-dia-39', 'explorador', 39, 'Libro de Job 2'),
  ('explorador-dia-40', 'explorador', 40, 'Libro de Job 42'),
  ('explorador-dia-41', 'explorador', 41, 'Libro de los Salmos 1; 15; 19'),
  ('explorador-dia-42', 'explorador', 42, 'Libro de los Salmos 23; 24; 27'),
  ('explorador-dia-43', 'explorador', 43, 'Libro de los Salmos 37'),
  ('explorador-dia-44', 'explorador', 44, 'Libro de los Salmos 39'),
  ('explorador-dia-45', 'explorador', 45, 'Libro de los Salmos 42'),
  ('explorador-dia-46', 'explorador', 46, 'Libro de los Salmos 46'),
  ('explorador-dia-47', 'explorador', 47, 'Libro de los Salmos 67'),
  ('explorador-dia-48', 'explorador', 48, 'Libro de los Salmos 90; 91'),
  ('explorador-dia-49', 'explorador', 49, 'Libro de los Salmos 92; 97'),
  ('explorador-dia-50', 'explorador', 50, 'Libro de los Salmos 98; 100; 117'),
  ('explorador-dia-51', 'explorador', 51, 'Libro de los Salmos 119:1-80'),
  ('explorador-dia-52', 'explorador', 52, 'Libro de los Salmos 119:81-176'),
  ('explorador-dia-53', 'explorador', 53, 'Libro de los Salmos 121; 125; 150'),
  ('explorador-dia-54', 'explorador', 54, 'Libro de Proverbios 1'),
  ('explorador-dia-55', 'explorador', 55, 'Libro de Proverbios 3'),
  ('explorador-dia-56', 'explorador', 56, 'Libro de Proverbios 4'),
  ('explorador-dia-57', 'explorador', 57, 'Libro de Proverbios 10'),
  ('explorador-dia-58', 'explorador', 58, 'Libro de Proverbios 15'),
  ('explorador-dia-59', 'explorador', 59, 'Libro de Proverbios 20'),
  ('explorador-dia-60', 'explorador', 60, 'Libro de Proverbios 25'),
  ('explorador-dia-61', 'explorador', 61, 'Libro de Eclesiastés 1'),
  ('pionero-dia-1', 'pionero', 1, 'Ec 3'),
  ('pionero-dia-2', 'pionero', 2, 'Ec 5'),
  ('pionero-dia-3', 'pionero', 3, 'Ec 7'),
  ('pionero-dia-4', 'pionero', 4, 'Ec 11,12'),
  ('pionero-dia-5', 'pionero', 5, 'Is 5'),
  ('pionero-dia-6', 'pionero', 6, 'Is 11'),
  ('pionero-dia-7', 'pionero', 7, 'Is 26:1-12; 35'),
  ('pionero-dia-8', 'pionero', 8, 'Is 40'),
  ('pionero-dia-9', 'pionero', 9, 'Is 43'),
  ('pionero-dia-10', 'pionero', 10, 'Is 52:13-15; 53'),
  ('pionero-dia-11', 'pionero', 11, 'Is 58'),
  ('pionero-dia-12', 'pionero', 12, 'Is 60'),
  ('pionero-dia-13', 'pionero', 13, 'Is 61'),
  ('pionero-dia-14', 'pionero', 14, 'Jr 9:23-26'),
  ('pionero-dia-15', 'pionero', 15, 'Jr 10:1-16'),
  ('pionero-dia-16', 'pionero', 16, 'Jr 18:1-6'),
  ('pionero-dia-17', 'pionero', 17, 'Jr 26'),
  ('pionero-dia-18', 'pionero', 18, 'Jr 36'),
  ('pionero-dia-19', 'pionero', 19, 'Jr 52:1-11'),
  ('pionero-dia-20', 'pionero', 20, 'Dn 1'),
  ('pionero-dia-21', 'pionero', 21, 'Dn 2'),
  ('pionero-dia-22', 'pionero', 22, 'Dn 3'),
  ('pionero-dia-23', 'pionero', 23, 'Dn 4'),
  ('pionero-dia-24', 'pionero', 24, 'Dn 5'),
  ('pionero-dia-25', 'pionero', 25, 'Dn 6'),
  ('pionero-dia-26', 'pionero', 26, 'Dn 7'),
  ('pionero-dia-27', 'pionero', 27, 'Dn 8'),
  ('pionero-dia-28', 'pionero', 28, 'Dn 9'),
  ('pionero-dia-29', 'pionero', 29, 'Dn 10'),
  ('pionero-dia-30', 'pionero', 30, 'Dn 11'),
  ('pionero-dia-31', 'pionero', 31, 'Dn 12'),
  ('pionero-dia-32', 'pionero', 32, 'Joel 2:12-31'),
  ('pionero-dia-33', 'pionero', 33, 'Am 7:10-16; 8:4-11'),
  ('pionero-dia-34', 'pionero', 34, 'Jon 1'),
  ('pionero-dia-35', 'pionero', 35, 'Jon 2'),
  ('pionero-dia-36', 'pionero', 36, 'Jn 3 y 4'),
  ('pionero-dia-37', 'pionero', 37, 'Mq 4'),
  ('pionero-dia-38', 'pionero', 38, 'Ag 2'),
  ('pionero-dia-39', 'pionero', 39, 'Zc 4'),
  ('pionero-dia-40', 'pionero', 40, 'Mt 3,4'),
  ('pionero-dia-41', 'pionero', 41, 'Mt 1'),
  ('pionero-dia-42', 'pionero', 42, 'Mt 2'),
  ('pionero-dia-43', 'pionero', 43, 'Mt 3'),
  ('pionero-dia-44', 'pionero', 44, 'Mt 4'),
  ('pionero-dia-45', 'pionero', 45, 'Mt 5'),
  ('pionero-dia-46', 'pionero', 46, 'Mt 6'),
  ('pionero-dia-47', 'pionero', 47, 'Mt 7'),
  ('pionero-dia-48', 'pionero', 48, 'Mt 8'),
  ('pionero-dia-49', 'pionero', 49, 'Mt 9'),
  ('pionero-dia-50', 'pionero', 50, 'Mt 10'),
  ('pionero-dia-51', 'pionero', 51, 'Mt 11'),
  ('pionero-dia-52', 'pionero', 52, 'Mt 12'),
  ('pionero-dia-53', 'pionero', 53, 'Mt 13'),
  ('pionero-dia-54', 'pionero', 54, 'Mt 14'),
  ('pionero-dia-55', 'pionero', 55, 'Mt 15'),
  ('pionero-dia-56', 'pionero', 56, 'Mt 16'),
  ('pionero-dia-57', 'pionero', 57, 'Mt 17'),
  ('pionero-dia-58', 'pionero', 58, 'Mt 18'),
  ('pionero-dia-59', 'pionero', 59, 'Mt 19'),
  ('pionero-dia-60', 'pionero', 60, 'Mt 20'),
  ('pionero-dia-61', 'pionero', 61, 'Mt 21'),
  ('pionero-dia-62', 'pionero', 62, 'Mt 22'),
  ('pionero-dia-63', 'pionero', 63, 'Mt 23'),
  ('excursionista-dia-1', 'excursionista', 1, 'Mt 24'),
  ('excursionista-dia-2', 'excursionista', 2, 'Mt 25'),
  ('excursionista-dia-3', 'excursionista', 3, 'Mt 26:1-35'),
  ('excursionista-dia-4', 'excursionista', 4, 'Mt 26:36-75'),
  ('excursionista-dia-5', 'excursionista', 5, 'Mt 27:1-31'),
  ('excursionista-dia-6', 'excursionista', 6, 'Mt 27:32-56'),
  ('excursionista-dia-7', 'excursionista', 7, 'Mt 27:57-66'),
  ('excursionista-dia-8', 'excursionista', 8, 'Mt 28'),
  ('excursionista-dia-9', 'excursionista', 9, 'Mr 7'),
  ('excursionista-dia-10', 'excursionista', 10, 'Mr 9'),
  ('excursionista-dia-11', 'excursionista', 11, 'Mr 10'),
  ('excursionista-dia-12', 'excursionista', 12, 'Mr 11'),
  ('excursionista-dia-13', 'excursionista', 13, 'Mr 12'),
  ('excursionista-dia-14', 'excursionista', 14, 'Mr 16'),
  ('excursionista-dia-15', 'excursionista', 15, 'Lc 1:4-25'),
  ('excursionista-dia-16', 'excursionista', 16, 'Lc 1:26-66'),
  ('excursionista-dia-17', 'excursionista', 17, 'Lc 2:21-38'),
  ('excursionista-dia-18', 'excursionista', 18, 'Lc 2:39-52'),
  ('excursionista-dia-19', 'excursionista', 19, 'Lc 7:18-28'),
  ('excursionista-dia-20', 'excursionista', 20, 'Lc 8'),
  ('excursionista-dia-21', 'excursionista', 21, 'Lc 10:1-37'),
  ('excursionista-dia-22', 'excursionista', 22, 'Lc 10:38-42;11:1-13'),
  ('excursionista-dia-23', 'excursionista', 23, 'Lc 12'),
  ('excursionista-dia-24', 'excursionista', 24, 'Lc 13'),
  ('excursionista-dia-25', 'excursionista', 25, 'Lc 14'),
  ('excursionista-dia-26', 'excursionista', 26, 'Lc 15'),
  ('excursionista-dia-27', 'excursionista', 27, 'Lc 16:1-17'),
  ('excursionista-dia-28', 'excursionista', 28, 'Lc 17'),
  ('excursionista-dia-29', 'excursionista', 29, 'Lc 18'),
  ('excursionista-dia-30', 'excursionista', 30, 'Lc 19'),
  ('excursionista-dia-31', 'excursionista', 31, 'Lc 21'),
  ('excursionista-dia-32', 'excursionista', 32, 'Lc 22'),
  ('excursionista-dia-33', 'excursionista', 33, 'Lc 23'),
  ('excursionista-dia-34', 'excursionista', 34, 'Lc 24'),
  ('excursionista-dia-35', 'excursionista', 35, 'Jn 1'),
  ('excursionista-dia-36', 'excursionista', 36, 'Jn 2'),
  ('excursionista-dia-37', 'excursionista', 37, 'Jn 3'),
  ('excursionista-dia-38', 'excursionista', 38, 'Jn 4'),
  ('excursionista-dia-39', 'excursionista', 39, 'Jn 5'),
  ('excursionista-dia-40', 'excursionista', 40, 'Jn 6:1-21'),
  ('excursionista-dia-41', 'excursionista', 41, 'Jn 6:22-71'),
  ('excursionista-dia-42', 'excursionista', 42, 'Jn 8:1-38'),
  ('excursionista-dia-43', 'excursionista', 43, 'Jn 9'),
  ('excursionista-dia-44', 'excursionista', 44, 'Jn 10'),
  ('excursionista-dia-45', 'excursionista', 45, 'Jn 11:1-46'),
  ('excursionista-dia-46', 'excursionista', 46, 'Jn 12'),
  ('excursionista-dia-47', 'excursionista', 47, 'Jn 13'),
  ('excursionista-dia-48', 'excursionista', 48, 'Jn 14'),
  ('excursionista-dia-49', 'excursionista', 49, 'Jn 15'),
  ('excursionista-dia-50', 'excursionista', 50, 'Jn 17'),
  ('excursionista-dia-51', 'excursionista', 51, 'Jn 18'),
  ('excursionista-dia-52', 'excursionista', 52, 'Jn 19'),
  ('excursionista-dia-53', 'excursionista', 53, 'Jn 20'),
  ('excursionista-dia-54', 'excursionista', 54, 'Jn 21'),
  ('excursionista-dia-55', 'excursionista', 55, 'He 1'),
  ('excursionista-dia-56', 'excursionista', 56, 'He 2'),
  ('excursionista-dia-57', 'excursionista', 57, 'He 3'),
  ('excursionista-dia-58', 'excursionista', 58, 'He 4'),
  ('excursionista-dia-59', 'excursionista', 59, 'He 5'),
  ('excursionista-dia-60', 'excursionista', 60, 'He 6'),
  ('excursionista-dia-61', 'excursionista', 61, 'He 7'),
  ('excursionista-dia-62', 'excursionista', 62, 'He 8'),
  ('guia-dia-1', 'guia', 1, 'He 9:1-31'),
  ('guia-dia-2', 'guia', 2, 'He 9:32-43'),
  ('guia-dia-3', 'guia', 3, 'He 10'),
  ('guia-dia-4', 'guia', 4, 'He 11'),
  ('guia-dia-5', 'guia', 5, 'He 12'),
  ('guia-dia-6', 'guia', 6, 'He 13'),
  ('guia-dia-7', 'guia', 7, 'He 14'),
  ('guia-dia-8', 'guia', 8, 'He 16'),
  ('guia-dia-9', 'guia', 9, 'He 17:1-15'),
  ('guia-dia-10', 'guia', 10, 'He 17:16-34'),
  ('guia-dia-11', 'guia', 11, 'He 18'),
  ('guia-dia-12', 'guia', 12, 'He 19:1-22'),
  ('guia-dia-13', 'guia', 13, 'He 19:23-41'),
  ('guia-dia-14', 'guia', 14, 'He 20'),
  ('guia-dia-15', 'guia', 15, 'He 21:17-40; 22:1-16'),
  ('guia-dia-16', 'guia', 16, 'He 23'),
  ('guia-dia-17', 'guia', 17, 'He 24'),
  ('guia-dia-18', 'guia', 18, 'He 25'),
  ('guia-dia-19', 'guia', 19, 'He 26'),
  ('guia-dia-20', 'guia', 20, 'He 27'),
  ('guia-dia-21', 'guia', 21, 'He 28'),
  ('guia-dia-22', 'guia', 22, 'Rm 12'),
  ('guia-dia-23', 'guia', 23, 'Rm13,14'),
  ('guia-dia-24', 'guia', 24, '1 Co 13'),
  ('guia-dia-25', 'guia', 25, '2 Co 5:11-21'),
  ('guia-dia-26', 'guia', 26, '2 Co 11:16-33; 12:1-10'),
  ('guia-dia-27', 'guia', 27, 'Gal 5:16-26; 6:1-10'),
  ('guia-dia-28', 'guia', 28, 'Ef 5:1-21'),
  ('guia-dia-29', 'guia', 29, 'Ef 6'),
  ('guia-dia-30', 'guia', 30, 'Fil 4'),
  ('guia-dia-31', 'guia', 31, 'Col 3'),
  ('guia-dia-32', 'guia', 32, '1Ts 4:13-18'),
  ('guia-dia-33', 'guia', 33, '1 Ts 5'),
  ('guia-dia-34', 'guia', 34, '2 Ts 2, 3'),
  ('guia-dia-35', 'guia', 35, '1Tm 4:6-16'),
  ('guia-dia-36', 'guia', 36, '1 Tm 5:1-16; 6:11-21'),
  ('guia-dia-37', 'guia', 37, '2 Tm 2'),
  ('guia-dia-38', 'guia', 38, '2 Tm 3'),
  ('guia-dia-39', 'guia', 39, 'Flm'),
  ('guia-dia-40', 'guia', 40, 'Hb 11'),
  ('guia-dia-41', 'guia', 41, 'Stg l'),
  ('guia-dia-42', 'guia', 42, 'Stg 3'),
  ('guia-dia-43', 'guia', 43, 'Stg 5:7-20'),
  ('guia-dia-44', 'guia', 44, '1 Pe 1'),
  ('guia-dia-45', 'guia', 45, '1 Pe 5:1-11'),
  ('guia-dia-46', 'guia', 46, '2 Pe 3'),
  ('guia-dia-47', 'guia', 47, '1 Jn 2'),
  ('guia-dia-48', 'guia', 48, '1 Jn 3'),
  ('guia-dia-49', 'guia', 49, '1 Jn 4'),
  ('guia-dia-50', 'guia', 50, '1 Jn 5'),
  ('guia-dia-51', 'guia', 51, 'Jd 1:17-25'),
  ('guia-dia-52', 'guia', 52, 'Ap 1'),
  ('guia-dia-53', 'guia', 53, 'Ap 2'),
  ('guia-dia-54', 'guia', 54, 'Ap 3'),
  ('guia-dia-55', 'guia', 55, 'Ap 7:9-17'),
  ('guia-dia-56', 'guia', 56, 'Ap 12'),
  ('guia-dia-57', 'guia', 57, 'Ap 13'),
  ('guia-dia-58', 'guia', 58, 'Ap 14'),
  ('guia-dia-59', 'guia', 59, 'Ap 19'),
  ('guia-dia-60', 'guia', 60, 'Ap 20'),
  ('guia-dia-61', 'guia', 61, 'Ap 21');

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.conquistador_classes, public.bible_reading_items, public.specialty_areas, public.specialties TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_progress TO authenticated;
